- name: Deploy to EC2
  run: |
    echo "${{ secrets.EC2_KEY }}" > key.pem
    chmod 400 key.pem

    scp -o StrictHostKeyChecking=no -i key.pem index.html ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu/

    ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
      sudo mv /home/ubuntu/index.html /var/www/html/index.html
      sudo systemctl restart nginx
    EOF
